config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect("/documents")

  get "/documents/publishing-guidance" => "new_document#guidance", as: :guidance
  get "/documents/new" => "new_document#choose_supertype", as: :new_document
  get "/documents/choose-document-type" => "new_document#choose_document_type", as: :choose_document_type
  post "/documents/create" => "new_document#create", as: :create_document

  get "/documents" => "documents#index"

  scope "/documents/:document" do
    get "" => "documents#show", as: :document
    patch "" => "documents#update"
    delete "" => "documents#destroy"
    get "/edit" => "documents#edit", as: :edit_document
    get "/generate-path" => "documents#generate_path", as: :generate_path
    get "/delete-draft" => "documents#confirm_delete_draft", as: :delete_draft

    get "/publish" => "publish#confirmation", as: :publish_confirmation
    post "/publish" => "publish#publish"
    get "/published" => "publish#published", as: :published

    get "/schedule-proposal" => "schedule_proposal#edit"
    post "/schedule-proposal" => "schedule_proposal#update"
    delete "/schedule-proposal" => "schedule_proposal#destroy"

    get "/schedule/new" => "schedule#new", as: :new_schedule
    post "/schedule/new" => "schedule#create", as: :create_schedule
    get "/schedule/edit" => "schedule#edit", as: :edit_schedule
    post "/schedule/edit" => "schedule#update", as: :update_schedule
    delete "/schedule" => "schedule#destroy"
    get "/scheduled" => "schedule#scheduled", as: :scheduled

    post "/internal_notes" => "internal_notes#create", as: :create_internal_note

    get "/debug" => "debug#index", as: :debug_document

    post "/submit-for-2i" => "review#submit_for_2i", as: :submit_document_for_2i
    post "/approve" => "review#approve", as: :approve_document

    get "/tags" => "tags#edit", as: :tags
    post "/tags" => "tags#update"

    get "/preview" => "preview#show", as: :preview_document
    post "/create-preview" => "preview#create", as: :create_preview

    get "/withdraw" => "withdraw#new", as: :withdraw
    post "/withdraw" => "withdraw#create"

    get "/unwithdraw" => "unwithdraw#confirm", as: :confirm_unwithdraw
    post "/unwithdraw" => "unwithdraw#unwithdraw", as: :unwithdraw

    get "/remove" => "remove#remove", as: :remove

    get "/images" => "images#index", as: :images
    post "/images" => "images#create", as: :create_image
    get "/images/:image_id/download" => "images#download", as: :download_image
    get "/images/:image_id/crop" => "images#crop", as: :crop_image
    patch "/images/:image_id/crop" => "images#update_crop"
    get "/images/:image_id/edit" => "images#edit", as: :edit_image
    patch "/images/:image_id/edit" => "images#update", as: :update_image
    delete "/images/:image_id" => "images#destroy", as: :destroy_image

    post "/lead-image/:image_id" => "lead_image#choose", as: :choose_lead_image
    delete "/lead-image" => "lead_image#remove", as: :remove_lead_image

    get "/topics" => "topics#edit", as: :topics
    patch "/topics" => "topics#update", as: :update_topics

    get "/backdate" => "backdate#edit", as: :backdate
    post "/backdate" => "backdate#update"
    delete "/backdate" => "backdate#destroy"

    get "/access-limit" => "access_limit#edit", as: :access_limit
    post "/access-limit" => "access_limit#update"

    post "/editions" => "editions#create", as: :create_edition

    get "/contact-embed" => "contact_embed#new"
    post "/contact-embed" => "contact_embed#create"

    post "/govspeak-preview" => "govspeak_preview#to_html", as: :govspeak_preview

    get "/file-attachments" => "file_attachments#index", as: :file_attachments
    post "/file-attachments" => "file_attachments#create", as: :create_file_attachment
    get "/file-attachments/:file_attachment_id" => "file_attachments#show", as: :file_attachment
    get "/file-attachments/:file_attachment_id/preview" => "file_attachments#preview", as: :preview_file_attachment
    get "/file-attachments/:file_attachment_id/edit" => "file_attachments#edit", as: :edit_file_attachment
    patch "/file-attachments/:file_attachment_id/edit" => "file_attachments#update", as: :update_file_attachment
    delete "/file-attachments/:file_attachment_id" => "file_attachments#destroy", as: :destroy_file_attachment
  end

  get "/healthcheck", to: proc { [200, {}, %w[OK]] }

  get "/how-to-use-publisher" => "publisher_information#how_to_use_publisher", as: :how_to_use_publisher
  get "/beta-capabilities" => "publisher_information#beta_capabilities", as: :beta_capabilities
  get "/publisher-updates" => "publisher_information#publisher_updates", as: :publisher_updates

  get "/video-embed" => "video_embed#new", as: :video_embed
  post "/video-embed" => "video_embed#create", as: :create_video_embed

  scope via: :all do
    match "/400" => "errors#bad_request"
    match "/404" => "errors#not_found"
    match "/422" => "errors#unprocessable_entity"
    match "/500" => "errors#internal_server_error"
  end

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  if Rails.env.test?
    get "/government/*all", to: proc { [200, {}, ["You've been redirected"]] }
  end
end

app/models/topic.rb
# frozen_string_literal: true

class Topic
  include ActiveModel::Model

  def self.govuk_homepage(index)
    find(TopicIndex::GOVUK_HOMEPAGE_CONTENT_ID, index)
  end

  def self.find(topic_content_id, index)
    raw_topic = index.lookup(topic_content_id)
    raw_topic ? new(raw_topic.merge(index: index)) : nil
  end

  attr_accessor :title, :child_content_ids, :legacy_topic_content_ids, :parent_content_id, :content_id, :index
  delegate :hash, to: :content_id

  def ==(other)
    content_id == other.content_id
  end

  alias_method :eql?, :==

  def breadcrumb
    ancestors + [self]
  end

  def children
    child_content_ids.map { |child_content_id| Topic.find(child_content_id, index) }
  end

  def parent
    Topic.find(parent_content_id, index)
  end

  def ancestors
    parent ? parent.ancestors + [parent] : []
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  rescue_from GdsApi::BaseError do |e|
    GovukError.notify(e)
    render "#{action_name}_api_down", status: :service_unavailable
  end

  def edit
    @edition = Edition.find_current(document: params[:document])
    @version = @edition.document_topics.version
    @topics = @edition.topics
  end

  def update
    result = Topics::UpdateInteractor.call(params: params, user: current_user)
    api_conflict, api_error = result.to_h.values_at(:api_conflict, :api_error)

    if api_conflict
      redirect_to topics_path(params[:document]),
                  alert_with_description: t("topics.edit.flashes.topic_update_conflict")
    elsif api_error
      redirect_to document_path(params[:document]),
                  alert_with_description: t("documents.show.flashes.topic_update_error")
    else
      redirect_to document_path(params[:document]),
                  notice: t("documents.show.flashes.topics_updated")
    end
  end
end

app/views/topics/edit.html.erb
<% content_for :back_link, render_back_link(href: document_path(@edition.document)) %>
<% content_for :title, t("topics.edit.title", title: @edition.title_or_fallback) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p class="govuk-body"><%= t("topics.edit.description") %></p>
  </div>

  <div class="govuk-grid-column-one-third">
    <div class="gem-c-related-navigation">
      <nav role="navigation" class="gem-c-related-navigation__nav-section">
        <ul class="gem-c-related-navigation__link-list">
          <li class="gem-c-related-navigation__link">
            <a href="https://www.gov.uk/guidance/how-to-publish-on-gov-uk/creating-and-updating-pages#add-topic-tagging"
               class="gem-c-related-navigation__section-link gem-c-related-navigation__section-link--other"
               data-gtm="topic-tagging-guidance"><%= t("topics.edit.link_guidance") %></a>
          </li>
          <li class="gem-c-related-navigation__link">
            <a href="<%= Plek.new.external_url_for('support') + '/taxonomy_new_topic_request/new' %>"
               class="gem-c-related-navigation__section-link gem-c-related-navigation__section-link--other"
               data-gtm="new-topic-request"><%= t("topics.edit.link_suggest_new") %></a>
          </li>
          <li class="gem-c-related-navigation__link">
            <a href="<%= Plek.new.external_url_for('support') + '/taxonomy_change_topic_request/new' %>"
               class="gem-c-related-navigation__section-link gem-c-related-navigation__section-link--other"
               data-gtm="change-topic-request"><%= t("topics.edit.link_suggest_change") %></a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

<% def unroll(topic) %>
  <li>
    <div class="govuk-checkboxes__item">
      <%= tag.input type: "checkbox",
        id: "topic-#{topic.content_id}",
        class: "govuk-checkboxes__input",
        name: "topics[]",
        value: topic.content_id,
        checked: @topics.include?(topic),
        data: {
          gtm: "choose-topics",
          "gtm-value": topic.title
        } %>

      <%= tag.label for: "topic-#{topic.content_id}", class:"govuk-label govuk-checkboxes__label" do %>
        <%= topic.title %>
      <% end %>
    </div>

    <% if topic.children.any? %>
      <ul class="govuk-list">
        <% topic.children.each do |child_topic| %>
          <% unroll(child_topic) %>
        <% end %>
      </ul>
    <% end %>
  </li>
<% end %>

<%= form_tag update_topics_path(@edition.document), data: { gtm: "confirm-edit-topics" }, method: :patch do %>
  <h2 class="govuk-heading-m"><%= t("topics.edit.selected_title") %></h2>
  <miller-columns-selected class="miller-columns-selected" id="selected-items" for="miller-columns"></miller-columns-selected>

  <div class="app-js-only">
    <%= render "components/autocomplete", {
      id: "topics-autocomplete",
      name: "topics-autocomplete",
      label: {
        text: "Search topics",
        bold: true
      },
      type: "topics",
      search: true
    } %>
  </div>

  <miller-columns id="miller-columns" class="miller-columns" for="taxonomy" selected="selected-items">
  <ul id="taxonomy" class="govuk-list">
    <% Topic.govuk_homepage(@edition.document_topics.index).children.each do |topic| %>
      <% unroll(topic) %>
    <% end %>
  </ul>
  </miller-columns>

  <%= hidden_field_tag :version, @version %>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= render "govuk_publishing_components/components/details", {
        title: t("topics.edit.warning_title")
      } do %>
        <div data-gtm="topic-edit-warning" data-gtm-visibility-tracking="true">
          <%= t("topics.edit.warning_description") %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render "govuk_publishing_components/components/button", {
    text: "Save", margin_bottom: true
  } %>
<% end %>

app/views/topics/edit_api_down.html.erb
<% content_for :back_link, render_back_link(href: document_path(@edition.document)) %>
<% content_for :title, t("topics.edit.title", title: @edition.title_or_fallback) %>

<p class="govuk-body">
  <%= t("topics.edit.api_down") %>
</p>