config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect("/documents")

  get "/documents/publishing-guidance" => "new_document#guidance", as: :guidance
  get "/documents/new" => "new_document#choose_supertype", as: :new_document
  get "/documents/choose-document-type" => "new_document#choose_document_type", as: :choose_document_type
  post "/documents/create" => "new_document#create", as: :create_document

  get "/documents" => "documents#index"

  scope "/documents/:document" do
    get "" => "documents#show", as: :document
    patch "" => "documents#update"
    delete "" => "documents#destroy"
    get "/edit" => "documents#edit", as: :edit_document
    get "/generate-path" => "documents#generate_path", as: :generate_path
    get "/delete-draft" => "documents#confirm_delete_draft", as: :delete_draft

    get "/publish" => "publish#confirmation", as: :publish_confirmation
    post "/publish" => "publish#publish"
    get "/published" => "publish#published", as: :published

    get "/schedule-proposal" => "schedule_proposal#edit"
    post "/schedule-proposal" => "schedule_proposal#update"
    delete "/schedule-proposal" => "schedule_proposal#destroy"

    get "/schedule/new" => "schedule#new", as: :new_schedule
    post "/schedule/new" => "schedule#create", as: :create_schedule
    get "/schedule/edit" => "schedule#edit", as: :edit_schedule
    post "/schedule/edit" => "schedule#update", as: :update_schedule
    delete "/schedule" => "schedule#destroy"
    get "/scheduled" => "schedule#scheduled", as: :scheduled

    post "/internal_notes" => "internal_notes#create", as: :create_internal_note

    get "/debug" => "debug#index", as: :debug_document

    post "/submit-for-2i" => "review#submit_for_2i", as: :submit_document_for_2i
    post "/approve" => "review#approve", as: :approve_document

    get "/tags" => "tags#edit", as: :tags
    post "/tags" => "tags#update"

    get "/preview" => "preview#show", as: :preview_document
    post "/create-preview" => "preview#create", as: :create_preview

    get "/withdraw" => "withdraw#new", as: :withdraw
    post "/withdraw" => "withdraw#create"

    get "/unwithdraw" => "unwithdraw#confirm", as: :confirm_unwithdraw
    post "/unwithdraw" => "unwithdraw#unwithdraw", as: :unwithdraw

    get "/remove" => "remove#remove", as: :remove

    get "/images" => "images#index", as: :images
    post "/images" => "images#create", as: :create_image
    get "/images/:image_id/download" => "images#download", as: :download_image
    get "/images/:image_id/crop" => "images#crop", as: :crop_image
    patch "/images/:image_id/crop" => "images#update_crop"
    get "/images/:image_id/edit" => "images#edit", as: :edit_image
    patch "/images/:image_id/edit" => "images#update", as: :update_image
    delete "/images/:image_id" => "images#destroy", as: :destroy_image

    post "/lead-image/:image_id" => "lead_image#choose", as: :choose_lead_image
    delete "/lead-image" => "lead_image#remove", as: :remove_lead_image

    get "/topics" => "topics#edit", as: :topics
    patch "/topics" => "topics#update", as: :update_topics

    get "/backdate" => "backdate#edit", as: :backdate
    post "/backdate" => "backdate#update"
    delete "/backdate" => "backdate#destroy"

    get "/access-limit" => "access_limit#edit", as: :access_limit
    post "/access-limit" => "access_limit#update"

    post "/editions" => "editions#create", as: :create_edition

    get "/contact-embed" => "contact_embed#new"
    post "/contact-embed" => "contact_embed#create"

    post "/govspeak-preview" => "govspeak_preview#to_html", as: :govspeak_preview

    get "/file-attachments" => "file_attachments#index", as: :file_attachments
    post "/file-attachments" => "file_attachments#create", as: :create_file_attachment
    get "/file-attachments/:file_attachment_id" => "file_attachments#show", as: :file_attachment
    get "/file-attachments/:file_attachment_id/preview" => "file_attachments#preview", as: :preview_file_attachment
    get "/file-attachments/:file_attachment_id/edit" => "file_attachments#edit", as: :edit_file_attachment
    patch "/file-attachments/:file_attachment_id/edit" => "file_attachments#update", as: :update_file_attachment
    delete "/file-attachments/:file_attachment_id" => "file_attachments#destroy", as: :destroy_file_attachment
  end

  get "/healthcheck", to: proc { [200, {}, %w[OK]] }

  get "/how-to-use-publisher" => "publisher_information#how_to_use_publisher", as: :how_to_use_publisher
  get "/beta-capabilities" => "publisher_information#beta_capabilities", as: :beta_capabilities
  get "/publisher-updates" => "publisher_information#publisher_updates", as: :publisher_updates

  get "/video-embed" => "video_embed#new", as: :video_embed
  post "/video-embed" => "video_embed#create", as: :create_video_embed

  scope via: :all do
    match "/400" => "errors#bad_request"
    match "/404" => "errors#not_found"
    match "/422" => "errors#unprocessable_entity"
    match "/500" => "errors#internal_server_error"
  end

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  if Rails.env.test?
    get "/government/*all", to: proc { [200, {}, ["You've been redirected"]] }
  end
end

app/models/document.rb
# frozen_string_literal: true

# Represents all versions of a piece of content in a particular locale.
# The version of content that is draft or been on GOV.UK is represented as an
# edition model. Each edit a user has made to content is represented through a
# revision model on an edition.
#
# This model is mutable
class Document < ApplicationRecord
  attr_readonly :content_id, :locale

  belongs_to :created_by, class_name: "User", optional: true

  has_one :current_edition,
          -> { where(current: true) },
          class_name: "Edition",
          inverse_of: :document

  has_one :live_edition,
          -> { where(live: true) },
          class_name: "Edition",
          inverse_of: :document

  has_many :editions

  has_many :revisions

  has_many :timeline_entries

  enum imported_from: { whitehall: "whitehall" }, _prefix: true

  delegate :topics, to: :document_topics

  scope :with_current_edition, -> do
    join_tables = { current_edition: %i[revision status] }
    joins(join_tables).includes(join_tables)
  end

  scope :using_base_path, ->(base_path) do
    left_outer_joins(current_edition: { revision: :content_revision },
                     live_edition: { revision: :content_revision })
      .where("content_revisions.base_path": base_path)
  end

  def self.find_by_param(content_id_and_locale)
    content_id, locale = content_id_and_locale.split(":")
    find_by!(content_id: content_id, locale: locale)
  end

  def self.create_initial(content_id: SecureRandom.uuid,
                          document_type_id:,
                          locale: "en",
                          user: nil,
                          tags: {})
    transaction do
      document = create!(content_id: content_id,
                         locale: locale,
                         created_by: user)

      document.tap do |d|
        Edition.create_initial(
          document: d,
          user: user,
          tags: tags,
          document_type_id: document_type_id,
        )
      end
    end
  end

  def next_edition_number
    (editions.maximum(:number) || 0) + 1
  end

  def next_revision_number
    (revisions.maximum(:number) || 0) + 1
  end

  def to_param
    content_id + ":" + locale
  end

  def document_topics
    @document_topics ||= DocumentTopics.find_by_document(self, TopicIndex.new)
  end

  def newly_created?
    return false if !current_edition || !current_edition.first?

    current_edition.created_at == current_edition.updated_at
  end
end

app/models/document_type.rb
# frozen_string_literal: true

class DocumentType
  include InitializeWithHash

  attr_reader :contents, :id, :label, :managed_elsewhere, :publishing_metadata,
              :path_prefix, :tags, :guidance_govspeak, :description, :hint, :images,
              :topics, :check_path_conflict

  def self.find(id)
    item = all.find { |document_type| document_type.id == id }
    item || (raise RuntimeError, "Document type #{id} not found")
  end

  def self.all
    @all ||= begin
      hashes = YAML.load_file(Rails.root.join("app", "formats", "document_types.yml"))

      hashes.map do |hash|
        hash["contents"] = hash["contents"].to_a.map(&Formats::Field.method(:for))
        hash["tags"] = hash["tags"].to_a.map(&TagField.method(:new))
        hash["publishing_metadata"] = PublishingMetadata.new(hash["publishing_metadata"].to_h)
        hash["guidance"] = hash["guidance"].to_a.map(&Guidance.method(:new))
        new(hash)
      end
    end
  end

  def managed_elsewhere_url
    Plek.new.external_url_for(managed_elsewhere.fetch("hostname")) + managed_elsewhere.fetch("path")
  end

  def guidance_for(id)
    @guidance.find { |guidance| guidance.id == id }
  end

  class TagField
    include InitializeWithHash
    attr_reader :id, :label, :type, :document_type, :hint
  end

  class Guidance
    include InitializeWithHash
    attr_reader :id, :title, :body_govspeak
  end

  class PublishingMetadata
    include InitializeWithHash
    attr_reader :schema_name, :rendering_app
  end
end

app/models/versioning/document.rb
# frozen_string_literal: true

module Versioning
  class Document < ApplicationRecord
    self.table_name = "versioned_documents"

    before_create do
      # set a default value for last_edited_at works better than using DB default
      self.last_edited_at = Time.zone.now unless last_edited_at
    end

    attr_readonly :content_id, :locale, :document_type_id

    # rubocop:disable Rails/InverseOf
    belongs_to :created_by,
               class_name: "User",
               optional: true,
               foreign_key: :created_by_id

    belongs_to :last_edited_by,
               class_name: "User",
               optional: true,
               foreign_key: :last_edited_by_id

    has_one :current_edition,
            -> { where(current: true) },
            class_name: "Versioning::Edition"

    has_one :live_edition,
            -> { where(live: true) },
            class_name: "Versioning::Edition"
    # rubocop:enable Rails/InverseOf

    has_many :editions,
             class_name: "Versioning::Edition",
             dependent: :restrict_with_exception

    has_many :revisions,
             class_name: "Versioning::Revision",
             dependent: :restrict_with_exception

    delegate :topics, to: :document_topics

    delegate :title, :base_path, to: :current_edition, allow_nil: true, prefix: true
    delegate :title, :base_path, to: :live_edition, allow_nil: true, prefix: true

    def self.find_by_param(content_id_and_locale)
      content_id, locale = content_id_and_locale.split(":")
      find_by!(content_id: content_id, locale: locale)
    end

    def self.create_initial(content_id: SecureRandom.uuid,
                          document_type_id:,
                          locale: "en",
                          user: nil)
      transaction do
        document = create!(content_id: content_id,
                           locale: locale,
                           document_type_id: document_type_id,
                           created_by: user,
                           last_edited_at: Time.zone.now,
                           last_edited_by: user)

        document.tap { |d| Edition.create_initial(d, user) }
      end
    end

    def next_edition_number
      (editions.maximum(:number) || 0) + 1
    end

    def to_param
      content_id + ":" + locale
    end

    def document_type
      DocumentType.find(document_type_id)
    end

    def document_topics
      @document_topics_index ||= TopicIndexService.new
      DocumentTopics.find_by_document(self, @document_topics_index)
    end

    def update_last_edited_at(user, time = Time.zone.now)
      return if last_edited_at > time

      update!(last_edited_by: user, last_edited_at: time)
    end
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  def index
    if filter_params[:filters].empty? && current_user.organisation_content_id
      redirect_to documents_path(organisation: current_user.organisation_content_id)
      return
    end

    filter = EditionFilter.new(current_user, filter_params)
    @editions = filter.editions
    @filter_params = filter.filter_params
    @sort = filter.sort
  end

  def edit
    @edition = Edition.find_current(document: params[:document])
    assert_edition_state(@edition, &:editable?)
    @revision = @edition.revision
  end

  def show
    @edition = Edition.find_current(document: params[:document])
  end

  def confirm_delete_draft
    edition = Edition.find_current(document: params[:document])
    assert_edition_state(edition, &:editable?)
    redirect_to document_path(edition.document), confirmation: "documents/show/delete_draft"
  end

  def destroy
    result = Documents::DestroyInteractor.call(params: params, user: current_user)

    if result.api_error
      redirect_to document_path(params[:document]),
                  alert_with_description: t("documents.show.flashes.delete_draft_error")
    else
      redirect_to documents_path
    end
  end

  def update
    result = Documents::UpdateInteractor.call(params: params, user: current_user)
    edition, revision, issues, = result.to_h.values_at(:edition, :revision, :issues)

    if issues
      flash.now["requirements"] = {
        "items" => issues.items(link_options: issues_link_options(edition)),
      }

      render :edit,
             assigns: { edition: edition, revision: revision, issues: issues },
             status: :unprocessable_entity
    else
      redirect_to edition.document
    end
  end

  def generate_path
    edition = Edition.find_current(document: params[:document])
    base_path = PathGeneratorService.call(edition.document, params[:title])
    render plain: base_path
  end

private

  def filter_params
    {
      filters: params.slice(:title_or_url, :document_type, :status, :organisation).permit!,
      sort: params[:sort],
      page: params[:page],
      per_page: 50,
    }
  end

  def issues_link_options(edition)
    format_specific_options = edition.document_type.contents.each_with_object({}) do |field, memo|
      memo[field.id.to_sym] = { href: "##{field.id}-field" }
    end

    {
      title: { href: "#title-field" },
      summary: { href: "#summary-field" },
    }.merge(Hash[format_specific_options])
  end
end

app/views/documents/_nav.html.erb
<p>
  <%= link_to "Summary", document_path(@document) %>
  <%= link_to "Edit", edit_document_path(@document) %>
  <%= link_to "History", document_history_path(@document) %>
</p>

app/views/documents/edit.html.erb
<% content_for :back_link, render_back_link(href: document_path(@edition.document)) %>

<% if @edition.document.newly_created? %>
  <% content_for :title, t("documents.edit.title_new", document_type: @edition.document_type.label.downcase) %>
<% else %>
  <% content_for :title, t("documents.edit.title", title: @edition.title_or_fallback) %>
<% end %>

<%= form_for @edition.document,
  html: { class: "app-c-contextual-guidance__form" },
  data: {
    module: "edit-document-form",
    "url-preview-path": generate_path_path,
    "warn-before-unload": "true",
    gtm: "edit-document-submit"
  } do |f| %>

  <%
    title_contextual_guidance = {
      id: "title",
      html_for: "title-field"
    }
    if @edition.document_type.guidance_for("title")
      title_contextual_guidance.merge!({
        title: @edition.document_type.guidance_for("title").title,
        content: @edition.document_type.guidance_for("title").body_govspeak
      })
    end
  %>

  <%= render "govuk_publishing_components/components/contextual_guidance", title_contextual_guidance do %>
    <%= render "govuk_publishing_components/components/textarea", {
      label: {
        text: t("documents.edit.form_labels.title"),
        bold: true
      },
      id: "title-field",
      name: "revision[title]",
      value: @revision.title,
      error_items: @issues&.items_for(:title),
      rows: 2,
      maxlength: Requirements::ContentChecker::TITLE_MAX_LENGTH,
      data: { "url-preview": "input" }
    } do %>
      <%= render "components/input_length_suggester", {
        for_id: "title-field",
        show_from: 55,
        message: "Title should be under 65 characters. Current length: {count}",
      } %>
    <% end %>
  <% end %>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <%= render "components/url_preview", {
        title: t("documents.edit.url_preview.available"),
        default_message: t("documents.edit.url_preview.no_title"),
        error_message: t("documents.edit.url_preview.error"),
        website_root: Plek.new.website_root,
        base_path: @revision.base_path
      } %>
    </div>
  </div>

  <%
    summary_contextual_guidance = {
      id: "summary",
      html_for: "summary-field"
    }
    if @edition.document_type.guidance_for("title")
      summary_contextual_guidance.merge!({
        title: @edition.document_type.guidance_for("summary").title,
        content: @edition.document_type.guidance_for("summary").body_govspeak
      })
    end
  %>

  <%= render "govuk_publishing_components/components/contextual_guidance", summary_contextual_guidance do %>
    <%= render "govuk_publishing_components/components/textarea", {
      label: {
        text: t("documents.edit.form_labels.summary"),
        bold: true
      },
      id: "summary-field",
      name: "revision[summary]",
      value: @revision.summary,
      error_items: @issues&.items_for(:summary),
      rows: 4,
      maxlength: Requirements::ContentChecker::SUMMARY_MAX_LENGTH
    } do %>
      <%= render "components/input_length_suggester", {
        for_id: "summary-field",
        show_from: 120,
        message: "Summary should be under 160 characters. Current length: {count}",
      } %>
    <% end %>
  <% end %>

  <% @edition.document_type.contents.each do |field| %>
    <%= render "documents/fields/#{field.type}_input",
      field: field,
      edition: @edition,
      revision: @revision,
      issues: @issues
    %>
  <% end %>

  <% if @edition.document.live_edition %>
    <%= render "documents/edit/change_notes" %>
  <% end %>

  <%= render "govuk_publishing_components/components/button", {
    text: "Save", margin_bottom: true
  } %>
<% end %>

app/views/documents/forbidden.html.erb
<% content_for :title, t("documents.forbidden.title") %>

<div class="govuk-body" data-gtm="access-limit-forbidden" data-gtm-visibility-tracking="true">
  <%= t("documents.forbidden.description") %>
</div>

<div class="govuk-body">
  <% begin %>
    <% primary_org = Linkables.new("organisation")
      .by_content_id(@edition.primary_publishing_organisation_id) %>

    <% if primary_org %>
      <%= t("documents.forbidden.owner",
            primary_org: primary_org.fetch("internal_name")) %>
    <% end %>
  <% rescue GdsApi::BaseError; end %>
</div>

app/views/documents/history.html.erb
<% content_for :title, "History" %>

<%= render 'nav' %>

<% in_edition_number = @document.current_edition_number %>

<% unless @document.publication_state == "published-to-live" %>
<h2 class='govuk-heading-l'><%= in_edition_number.ordinalize %> edition (unpublished)</h2>
<% end %>

<% @document.versions.reverse.each do |version| %>
  <% if version.reify && version.reify.current_edition_number != in_edition_number %>
    <% in_edition_number = version.reify.current_edition_number %>
    <h2 class='govuk-heading-l'><%= in_edition_number.ordinalize %> edition</h2>
  <% end %>

  <h3 class='govuk-heading-m'>Document <%= version.event %></h3>

  <div>
  <% version.changeset.each do |attribute, (from, to)| %>
    <p>
      <% if attribute == "publication_state" && to == "published-to-live" %>
        <%= in_edition_number.ordinalize %> edition published to GOV.UK.
      <% end %>

      <% next if attribute.in?(%w[updated_at created_at id content_id locale publication_state current_edition_number]) %>

      <% if from.blank? %>
        <%= attribute.humanize %> added: <%= to.inspect %>
      <% elsif to.blank? %>
        <%= attribute.humanize %> removed
      <% else %>
        <%= attribute.humanize %> changed from <strike><%= (from || "").inspect %></strike>
        to <%= to.inspect %>
      <% end %>
    </p>
  <% end %>
  </div>

  <% if version.next %>
  <details class='govuk-details'>
    <summary class='govuk-details__summary'>This version</summary>
    <pre>
      <%= version.next.object %>
    </pre>
    <%= button_to "roll back to this version", roll_back_to_version_path(version) %>
  </details>
  <% end %>
<% end %>

app/views/documents/index.html.erb
<% content_for :title, t("documents.index.title") %>

<% content_for :title_side, render("govuk_publishing_components/components/button", {
  text: "Create new document",
  href: new_document_path,
  margin_bottom: true,
  data_attributes: { gtm: "new-document" }
}) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-one-quarter">
    <%= render "documents/index/filters" %>

    <hr class="govuk-section-break govuk-section-break--visible govuk-section-break--l">

    <p class="govuk-heading-s"> <%= t("documents.index.guidance.title") %></p>
    <p class="govuk-body">
      <%= link_to "Planning, writing and managing content", "https://www.gov.uk/topic/government-digital-guidance/content-publishing",
        class: "govuk-link",
        target: "_blank",
        data: { gtm: "content-publishing-guidance" } %>
    </p>
  </div>

  <div class="govuk-grid-column-three-quarters">
    <p class="govuk-body govuk-!-margin-bottom-1">
      <%= t("documents.index.search_results.summary_html", count: @editions.total_count) %>
    </p>

    <% if @editions.none? %>
      <div class="govuk-body">
        <%= govspeak_to_html t("documents.index.search_results.guidance_govspeak") %>
      </div>
    <% else %>
      <%= render "documents/index/results" %>
    <% end %>

    <% pages = { } %>

    <% page_info = t("documents.index.search_results.page_info",
                     page: @editions.current_page,
                     pages: @editions.total_pages) %>

    <% pages[:previous_page] = { url: documents_path(@filter_params.merge(page: @editions.prev_page)),
                                 label: page_info,
                                 title: "Previous page" } if @editions.prev_page %>

    <% pages[:next_page] = { url: documents_path(@filter_params.merge(page: @editions.next_page)),
                             label: page_info,
                             title: "Next page" } if @editions.next_page %>

    <%= render "govuk_publishing_components/components/previous_and_next_navigation", pages %>
  </div>
</div>

app/views/documents/show.html.erb
<% content_for :back_link, render_back_link(href: documents_path) %>
<% content_for :title, @edition.title_or_fallback %>
<% content_for :context, @edition.document_type.label %>

<%= render "govuk_publishing_components/components/tabs", {
  panel_border: false,
  tabs: [
    {
      id: "edit-document",
      label: t("documents.show.tabs.summary"),
      title: t("documents.show.tabs.summary"),
      content: render("documents/show/summary_tab"),
      tab_data_attributes: { gtm: "summary-tab" }
    },
    {
      id: "document-history",
      label: t("documents.show.tabs.history"),
      title: t("documents.show.tabs.history"),
      content: render("documents/show/history_tab"),
      tab_data_attributes: { gtm: "history-tab" }
    }
  ]
} %>

app/views/documents/summary.html.erb
<%= content_for :title, @document.title %>

<%= render 'nav' %>

<h2 class='govuk-heading-l'>States</h2>

<p>
<% if @document.publication_state == "unpublished-edits" %>
  <% if @document.previewable_in_current_state? %>
    This document has changes that haven't been published to GOV.UK yet.
    <br/>
    <br/>
    All the fields required for preview have been filled in, so you can <a href='#'>preview this document</a> or publish it.
    <br/>
    <br/>
    <%= button_to "Publish this document", publish_document_path(@document), class: "govuk-button" %>
  <% else %>
    This document has changes that haven't been published to GOV.UK yet.
    <br/>
    <br/>
    You currently can't preview or publish this document, because it
    <%= link_to "needs a title and description", edit_document_path(@document) %>.
  <% end %>
<% else %>
  This document has been published and is <a href='#'>viewable on GOV.UK</a>.
<% end %>
</p>

<hr/>
<br/>

<p>
  Publication state:
  <% %w[unpublished-edits published-to-live].each do |state| %>
    <% if state == @document.publication_state %>
      <strong><%= state %></strong>
    <% else %>
      <%= state %>
    <% end %>
  <% end %>
</p>

<p>
  Validation state:
    <% if @document.previewable_in_current_state? %>
      Not enough info for publishing | <strong>OK to publish/preview</strong>
    <% else %>
      <strong>not enough info for publishing</strong> | OK to publish/preview
    <% end %>
</p>